.PHONY: help

help:
	echo ""
	echo "====================< Arc Make Help >===================="
	echo "Usage   : make <option> <command>"
	echo "option  : {list | get_all_tc | get_arm_tc | get_avr_tv |"
	echo "           get_riscv_tc | help} or <Project Name>"
	echo "command : default (implicit) | all | clean"
	echo "---------------------------------------------------------"
	echo "Project Name:"
	echo "* The project name is the name of directory under"
	echo "  src/project which needs to be built."
	echo "* To get the list of projects run 'make list'."
	echo "---------------------------------------------------------"
	echo "list:"
	echo "* This option lists the available projects."
	echo "get_all_tc:"
	echo "* This option fetches all the toolchains of supported"
	echo "  platforms."
	echo "get_arm_tc:"
	echo "* This option fetches ARM-v7 toolchain."
	echo "get_avr_tc:"
	echo "* This option fetches AVR-8 toolchain."
	echo "get_riscv_tc:"
	echo "* This option fetched RISC-V toolchain."
	echo "========================================================="
	echo ""
