/*
 * CYANCORE LICENSE
 * Copyrights (C) 2019, Cyancore Team
 *
 * File Name		: plat_vectors.S
 * Description		: This file contains platform vector of atmega328p
 * Primary Author	: Akash Kollipara [akashkollipara@gmail.com]
 * Organisation		: Cyancore Core-Team
 */

#include <asm.inc>

vectors platvectors
	jmp	int_1
	jmp	int_2
	jmp	int_3
	jmp	int_4
	jmp	int_5
	jmp	int_6
	jmp	int_7
	jmp	int_8
	jmp	int_9
	jmp	int_10
	jmp	int_11
	jmp	int_12
	jmp	int_13
	jmp	int_14
	jmp	int_15
	jmp	int_16
	jmp	int_17
	jmp	int_18
	jmp	int_19
	jmp	int_20
	jmp	int_21
	jmp	int_22
	jmp	int_23
	jmp	int_24
	jmp	int_25
	jmp	int_26
	jmp	int_27
	jmp	int_28
	jmp	int_29
	jmp	int_30
	jmp	int_31
	jmp	int_32
	jmp	int_33
	jmp	int_34
	jmp	int_35
	jmp	int_36
	jmp	int_37
	jmp	int_38
	jmp	int_39
	jmp	int_40
	jmp	int_41
	jmp	int_42
	jmp	int_43
	jmp	int_44
	jmp	int_45
	jmp	int_46
	jmp	int_47
	jmp	int_48
	jmp	int_49
	jmp	int_50
	jmp	int_51
	jmp	int_52
	jmp	int_53
	jmp	int_54
	jmp	int_55
	jmp	int_56
